import { sceneAssets } from "../scene-assets.js";

export const roomScene = Object.freeze({
  id: "room",
  title: "现在想从哪里开始？",
  titleByPhase: {
    morning: "早上想从哪里开始？",
    afternoon: "下午想从哪里开始？",
    dusk: "黄昏想从哪里开始？",
    lateNight: "深夜想从哪里开始？",
  },
  eyebrow: "你的房间",
  description: "书桌保存书写，公告板拼接主题，书架收藏成书；房门通向门外的信箱。",
  aspectRatio: 1456 / 816,
  initialFocusObjectId: "desk",
  layers: [
    {
      id: "background",
      type: "image",
      source: sceneAssets.room.background,
      alt: "安静温暖的正视房间，木地板与浅色墙面为家具留出清晰的布置空间。",
      z: 0,
    },
  ],
  objects: [
    {
      id: "rug",
      label: "地毯",
      kind: "decor",
      interactive: false,
      visualSource: sceneAssets.room.rug,
      hitArea: { x: 23.283, y: 83.701, width: 53.9835, height: 14.2157 },
      z: 10,
    },
    {
      id: "door",
      label: "房门",
      kind: "scene",
      visualSource: sceneAssets.room.doorClosed,
      hitArea: { x: 74.9313, y: 18.2598, width: 17.4451, height: 66.0539 },
      hintAnchor: { x: 83.65, y: 19.5 },
      hint: { title: "走到门外", text: "旧信箱就在门外" },
      dialogueId: "room.leave",
      action: { type: "scene", target: "doorway" },
      z: 20,
    },
    {
      id: "bulletin-board",
      label: "公告板",
      kind: "feature",
      visualSource: sceneAssets.room.bulletinBoard,
      hitArea: { x: 35.3022, y: 19.4853, width: 27.9533, height: 28.4314 },
      hintAnchor: { x: 49.2, y: 19.2 },
      hint: { title: "打开公告板", text: "把碎片摆成一个主题" },
      action: { type: "feature", target: "openBoard" },
      z: 30,
    },
    {
      id: "bookshelf",
      label: "书架",
      kind: "feature",
      movable: true,
      visualSource: sceneAssets.room.bookshelf,
      hitArea: { x: 5.2198, y: 19.3627, width: 22.4588, height: 68.3824 },
      hintAnchor: { x: 16.45, y: 19.75 },
      hint: { title: "打开书架", text: "翻看整理过的故事" },
      dialogueId: "room.bookshelf",
      action: { type: "feature", target: "openBookshelf" },
      z: 40,
    },
    {
      id: "plant",
      label: "绿植",
      kind: "decor",
      interactive: false,
      movable: true,
      visualSource: sceneAssets.room.plant,
      hitArea: { x: 25.9615, y: 61.152, width: 8.1731, height: 25.2451 },
      z: 50,
    },
    {
      id: "desk",
      label: "书桌",
      kind: "feature",
      movable: true,
      visualSource: sceneAssets.room.deskClosed,
      hitArea: { x: 34.6154, y: 60.9069, width: 32.0742, height: 28.1863 },
      hintAnchor: { x: 63.2, y: 59.9 },
      hint: { title: "前往书桌", text: "纸页还在等你" },
      dialogueId: "room.desk",
      action: { type: "feature", target: "openWorkbench" },
      z: 60,
    },
    {
      id: "desk-lamp",
      label: "台灯",
      kind: "light",
      movable: true,
      visualSource: sceneAssets.room.lampOff,
      hitArea: { x: 56.5247, y: 47.3039, width: 6.7995, height: 15.4412 },
      toggleState: {
        key: "light",
        defaultValue: false,
        off: {
          actionLabel: "打开台灯",
          statusText: "让暖光落在书桌上",
        },
        on: {
          actionLabel: "关掉台灯",
          statusText: "暖光正亮着，再点一次让房间暗下来",
        },
      },
      z: 70,
    },
    {
      id: "chair",
      label: "椅子",
      kind: "decor",
      interactive: false,
      movable: true,
      visualSource: sceneAssets.room.chairBack,
      hitArea: { x: 40.4533, y: 56.8627, width: 10.8516, height: 35.4167 },
      z: 80,
    },
  ],
});
