export function createAppState() {
  return {
    user: null,
    privacyUnlocked: false,
    journey: null,
    entries: [],
    entriesLoaded: false,
    topics: [],
    topicsLoaded: false,
    books: [],
    booksLoaded: false,
    letters: [],
    current: null,
    currentTopic: null,
    currentBook: null,
    workbenchMode: "fragments",
    fragmentDrawerOpen: false,
    topicDirectoryOpen: false,
    topicLayoutBusy: false,
    editorExpanded: false,
    dirty: false,
    busy: false,
    messageTimer: null,
  };
}
