export function createAppState() {
  return {
    user: null,
    privacyUnlocked: false,
    storyJourney: null,
    entries: [],
    entriesLoaded: false,
    topics: [],
    topicsLoaded: false,
    books: [],
    booksLoaded: false,
    letters: [],
    sentLetters: [],
    sentLettersLoaded: false,
    current: null,
    currentTopic: null,
    currentBook: null,
    currentIncomingLetter: null,
    currentSentLetter: null,
    browseMode: "category",
    selectedCategory: "fragment",
    selectedTag: null,
    mailboxMode: "sent",
    workbenchMode: "fragments",
    fragmentDrawerOpen: false,
    topicDirectoryOpen: false,
    topicLayoutBusy: false,
    editorExpanded: false,
    dirty: false,
    busy: false,
    messageTimer: null,
  };
}
